spring:
  application:
    name: transactions
  liquibase:
    change-log: "classpath:db/changelog/master.changelog.xml"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    property-naming-strategy: SNAKE_CASE
