services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: transactions
      MYSQL_USER: transaction-dev
      MYSQL_PASSWORD: transaction-dev
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck: # Define a health check for MySQL - Needed to the application starts correctly
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puser" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  application:
    build:
      context: ../../
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: transactions
      MYSQL_USER: transaction-dev
      MYSQL_PASS: transaction-dev
      TZ: America/Sao_Paulo